### ISSUE TITLE
Websites are not displayed

### ISSUE THREAD

**Issue by L4ma** [ceviixx/umami-Analytics-App#5]
**Describe the bug**
I have two websites in Umami, but they are not displayed in the app. However, when I create a website in the app, it is also displayed on the web. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 16 Pro
 - OS: iOS 18.2
 - Version 4.0.1

**Wich umami instance you're using::**
- Type: Cloud

**Comment by ceviixx** [comment]
Thinking this is an issue with the timestamp. 
I'm working on it and hope that next week an update can released.

**Comment by ceviixx** [comment]
It's also an bug in combination with the support of multiple hosts. 
This should be fixed with the new release (4.1.0).

**Comment by ceviixx** [comment]
@L4ma the new update is released. 
If you updated and it works, can u please give me feedback to close this issue?

**Comment by L4ma** [comment]
Unfortunately, the update does not work as hoped. I have two websites in Umami and one does not show the data. The loading times to display the data are unfortunately also a bit long.
Am 22. Dez. 2024, 16:28 +0100 schrieb Clemens ***@***.***>:

**Comment by ceviixx** [comment]
Did you tried do login again or delete and re install ?

**Comment by L4ma** [comment]
So after reinstalling, I see all data from both websites. However, the loading times have not improved. The loadingtime is approx. 7 seconds when I click on Overview.
Am 22. Dez. 2024, 17:53 +0100 schrieb Clemens ***@***.***>:

**Comment by ceviixx** [comment]
@L4ma nice that it now works - it was not the timestamp issue, it was the multiple host support. Mutliple host is complete remove in the new version, may there was something in the "Cache" / "App Store" on the update.

The loading speed is slow on cloud, because the api from umami self is really slow. Self hosted is the loading time much better then cloud.
Hopfully umami will excrete the sweet.
